---
title: "Dog Thermal Relations"
author: "Aziz Ur Rehman Zafar"
date: "3/12/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r find_slope, echo =F}
library(mblm)
find_slope = function(row_data){
  temp_df = data.frame(Stress = row_data, x = seq_along(row_data))
  median_lm = mblm(Stress ~ x, data = temp_df)
  #print(summary(median_lm))
  return(coef(median_lm)[2])
}
```

```{r se, echo =F}
se = function(data){
  return(sd(data)/sqrt(length(data)))
}
```

```{r impute, echo =F}
mode.for.impute = function(data.column){
  unique_elements <- na.omit(unique(data.column)) 
  #this finds the unique elements of the column,
  #except for NA
  table <- tabulate(match(data.column, unique_elements)) 
  #tabulate will count the frequencies of each unique element in the column
  unique_elements[table == max(table)] #this will identify the elements that 
  #have the same frequency
  #as the highest frequency identified by the tabulate function.
  #Therefore, if there are multiple modes, this function will return a vector 
  #of modes rather than 1 arbitrary mode.
}
impute = function(data.column){
  set.seed(0) #here I will set a seed for the random number generator to ensure that
  #my results are replicatable and I can test my code (it is tough to test code when
  # random number generator returns different results for each run!)
  categorical = T
  if (is.numeric(data.column)){
    imputing_statistic = mean(data.column, na.rm = T)
    categorical = F
    }
  #The above statement checks if data in a column is quantitative
  else {
    imputing_statistic = mode.for.impute(data.column)
    }
  #Otherwise, the data in the column is categorical (provided it is not numeric)
  if (categorical & length(imputing_statistic >1)){
    #In the case that data is categorical and there are more than 1 nodes, I want
    #to use randomly picked values for mode for each NA to attempt to preserve
    #the variation in the data set. If I simply use 1 mode, then I may be skewing
    #the data set and making my analysis biased towards the mode I have selected.
    
    indices.of.NAs = which(is.na(data.column)) 
    num.of.NAs = length(indices.of.NAs)
    modes = sample(imputing_statistic, num.of.NAs, replace = T)
    
    #Here, I am using sampling with replacement to randomly pick modes from the
    #vector of modes. 
    data.column = replace(data.column, indices.of.NAs, modes)
    #replacing NAs with the randomly selected modes
  }
  else {data.column[is.na(data.column)] = imputing_statistic} #Otherwise, I can
  #simply replace NAs with whatever statistic I have identified
  data.column
}
imputeapply = function(data){
  data.imputed = data.frame(lapply(data, impute))
  #This applies impute to each column in data (in only one line!)
  data.imputed
}
```

```{r in_to_cm,echo=F}
in_to_cm = function(data_column){
  return(data_column*2.54)
}

f.to.c <- function(x) (x - 32) / 1.8

```

```{r JJ data, echo =F,message=F,warning=F}
library(readxl)
library(dplyr)
library(MASS)
library(quantreg)
library(caret)
library(car)
library(tidyverse)
library(lmtest)
#JJ_ear = read_xlsx("June-July trials/June-July dog exercise trial data (ear temps).xlsx")
#JJ_ear = JJ_ear[-c(61:62),]
#JJ_regular = read_xlsx("June-July trials/June-July trial regular imaging data.xlsx")
#JJ_thermal = read_xlsx("June-July trials/June-July trials thermal imaging data.xlsx", sheet = 2)

#JJ_merged = merge(JJ_ear, JJ_regular, by = c("Dog's Name"))
#JJ_merged = merge(JJ_merged,JJ_thermal, by = c("Dog's Name"))
#JJ_merged = write.csv(JJ_merged, "merged_JJ.csv")

## if data processing is done, start here 

JJ_merged_cleaned = read_xlsx("June-July trials/merged_JJ_2.xlsx", sheet = 2) 
JJ_merged_eartemp = JJ_merged_cleaned %>% dplyr::select(starts_with("T(ear)"))%>%
  dplyr::select(-1)
JJ_merged_cleaned = cbind(JJ_merged_cleaned,
                      Slopes_ear =apply(X = JJ_merged_eartemp, MARGIN= 1,
                                    FUN = find_slope))
colnames(JJ_merged_cleaned)[2:14] = gsub(" ", "_",colnames(JJ_merged_cleaned)[2:14])
colnames(JJ_merged_cleaned) = gsub(".x", "",colnames(JJ_merged_cleaned))
colnames(JJ_merged_cleaned) = gsub("\\(", "",colnames(JJ_merged_cleaned))
colnames(JJ_merged_cleaned) = gsub("\\)", "",colnames(JJ_merged_cleaned))
colnames(JJ_merged_cleaned) = gsub(",", "",colnames(JJ_merged_cleaned))
colnames(JJ_merged_cleaned)[10:11] = gsub("_in", "",colnames(JJ_merged_cleaned))[10:11]
JJ_merged_cleaned$ear_length = in_to_cm(JJ_merged_cleaned$ear_length)
JJ_merged_cleaned$Front_leg_height_to_shoulder = in_to_cm(JJ_merged_cleaned$Front_leg_height_to_shoulder)
colnames(JJ_merged_cleaned) = gsub(",", "",colnames(JJ_merged_cleaned))
JJ_merged_cleaned$Breed_standardized = as.factor(JJ_merged_cleaned$Breed_standardized)
JJ_merged_cleaned <- within(JJ_merged_cleaned, 
                            Breed_standardized <- relevel(Breed_standardized, ref = "Mix"))
formula1 = as.formula(paste("Slopes_ear ~", paste(colnames(JJ_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
#### Ear Temps
print("June July EAR Temperatures")
lm1 = lm(formula1, data = JJ_merged_cleaned)
cooksd <- cooks.distance(lm1)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm1)
plot(stud_residuals)
shapiro.test(resid(lm1))
hist(resid(lm1))

table = summary(lm1)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC1 = stepAIC(lm1, trace = F, direction = "both")
print("June July EAR Temperatures -- BEST SUBSET")
#AIC
lrtest(lm1, lm(Slopes_ear ~ ., data=AIC1$model))
table = summary(lm(Slopes_ear ~ ., data=AIC1$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table

#### Max Eye temps
JJ_merged_eyetemp = JJ_merged_cleaned %>% dplyr::select(starts_with("M eye temp")) %>%
  dplyr::select(-1)
JJ_merged_cleaned = cbind(JJ_merged_cleaned,
                      Slopes_eye =apply(X = JJ_merged_eyetemp, MARGIN= 1,
                                    FUN = find_slope))
formula2 = as.formula(paste("Slopes_eye ~", paste(colnames(JJ_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
print("June July EYE Temperatures")
lmEye = lm(formula2, data =JJ_merged_cleaned)
table = summary(lmEye)
cooksd <- cooks.distance(lmEye)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lmEye)
plot(stud_residuals)
shapiro.test(resid(lmEye))
hist(resid(lmEye))


table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC2 = stepAIC(lmEye, trace = F, direction = "both")
#AIC
print("June July EYE Temperatures -- BEST SUBSET")
lrtest(lmEye, lm(Slopes_eye ~., data = AIC2$model))
table =summary(lm(Slopes_eye ~., data = AIC2$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table

#### Max Mouth temps
JJ_merged_mouthtemp = JJ_merged_cleaned %>% dplyr::select(starts_with("M mouth temp"))%>%
  dplyr::select(-1)
JJ_merged_cleaned = cbind(JJ_merged_cleaned,
                      Slopes_mouth =apply(X = JJ_merged_mouthtemp, MARGIN= 1,
                                    FUN = find_slope))
formula3 = as.formula(paste("Slopes_mouth ~", paste(colnames(JJ_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
lmMouth = lm(formula3, data =JJ_merged_cleaned)
print("June July MOUTH Temperatures")
table = summary(lmMouth)
cooksd <- cooks.distance(lmMouth)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lmMouth)
plot(stud_residuals)
shapiro.test(resid(lmMouth))
hist(resid(lmMouth))

table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC3 = stepAIC(lmMouth, trace = F, direction = "both")
print("June July MOUTH Temperatures -- BEST SUBSET")
lrtest(lmMouth, lm(Slopes_mouth ~., data = AIC3$model))
table = summary(lm(Slopes_mouth ~., data = AIC3$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
#### Nose temps
JJ_merged_nosetemp = JJ_merged_cleaned %>% dplyr::select(starts_with("M nose temp"))%>%
  dplyr::select(-1)
JJ_merged_cleaned = cbind(JJ_merged_cleaned,
                      Slopes_nose =apply(X = JJ_merged_nosetemp, MARGIN= 1,
                                    FUN = find_slope))
formula4 = as.formula(paste("Slopes_nose ~", paste(colnames(JJ_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
lmNose = lm(formula4, data =JJ_merged_cleaned)
print("June July NOSE Temperatures")
cooksd <- cooks.distance(lmNose)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lmNose)
plot(stud_residuals)
shapiro.test(resid(lmNose))
hist(resid(lmNose))
table = summary(lmNose)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC4 = stepAIC(lmNose, trace =F, direction = "both")
print("June July NOSE Temperatures -- BEST SUBSET")
lrtest(lmNose, lm(Slopes_nose ~., data = AIC4$model))
table = summary(lm(Slopes_nose ~., data = AIC4$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
```

```{r May data, echo=F, message=F,warning=F}
library(DMwR)
# May_ear = read_xlsx("May trials/May dog exercise trial data (ear temps).xlsx")
# May_ear = May_ear[-c(52:53),]
# May_regular = read_xlsx("May trials/May trial regular imaging data.xlsx")
# May_thermal = read_xlsx("May trials/May trial thermal imaging data.xlsx",sheet = 2)
# May_merged = merge(May_ear, May_regular, by = c("Dog's Name"))
# May_merged = merge(May_merged,May_thermal, by = c("Dog's Name"))
# May_merged = write.csv(May_merged, "merged_May.csv")

May_merged_cleaned = read_xlsx("May trials/merged_May_2.xlsx", sheet = 2) 
colnames(May_merged_cleaned)[2:14] = gsub(" ", "_",colnames(May_merged_cleaned)[2:14])
colnames(May_merged_cleaned) = gsub(".x", "",colnames(May_merged_cleaned))
colnames(May_merged_cleaned) = gsub("\\(", "",colnames(May_merged_cleaned))
colnames(May_merged_cleaned) = gsub("\\)", "",colnames(May_merged_cleaned))
colnames(May_merged_cleaned) = gsub(",", "",colnames(May_merged_cleaned))

May_merged_cleaned = imputeapply(May_merged_cleaned)
May_merged_cleaned$Breed_standardized = as.factor(May_merged_cleaned$Breed_standardized)
May_merged_cleaned <- within(May_merged_cleaned, 
                            Breed_standardized <- relevel(Breed_standardized, ref = "Mix"))
May_merged_eartemp = May_merged_cleaned %>% dplyr::select(starts_with("Tear"))%>%
  dplyr::select(-1)
May_merged_cleaned = cbind(May_merged_cleaned,
                      Slopes_ear =apply(X = May_merged_eartemp, MARGIN= 1,
                                    FUN = find_slope))
formula1 = as.formula(paste("Slopes_ear ~", paste(colnames(May_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
lm1 = lm(formula1, data = May_merged_cleaned)
print("May EAR Temperatures")
cooksd <- cooks.distance(lm1)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm1)
plot(stud_residuals)
shapiro.test(resid(lm1))
hist(resid(lm1))
#ummary(lm1)
AIC1 = stepAIC(lm1, trace = F, direction = "both")
print("May EAR Temperatures -- BEST SUBSET")
lrtest(lm1, lm(Slopes_ear ~., data = AIC1$model))
table = summary(lm(Slopes_ear ~., data = AIC1$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
##
May_merged_nosetemp = May_merged_cleaned %>% dplyr::select(starts_with("M.nose"))%>%
  dplyr::select(-1)
May_merged_cleaned = cbind(May_merged_cleaned,
                      Slopes_nose =apply(X = May_merged_nosetemp, MARGIN= 1,
                                    FUN = find_slope))
formula2 = as.formula(paste("Slopes_nose ~", paste(colnames(May_merged_cleaned)[2:14],
                            collapse = " +"), sep = ""))
lm2 = lm(formula2, data = May_merged_cleaned)
print("May NOSE Temperatures")
cooksd <- cooks.distance(lm2)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm2)
plot(stud_residuals)
shapiro.test(resid(lm2))
hist(resid(lm2))
table = summary(lm2)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC2 = stepAIC(lm2, trace = F, direction = "both")
print("May NOSE Temperatures -- BEST SUBSET")
lrtest(lm2, lm(Slopes_nose ~., data = AIC2$model))
table = summary(lm(Slopes_nose ~., data = AIC2$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
##
May_merged_eyetemp = May_merged_cleaned %>% dplyr::select(starts_with("M.eye"))%>%
  dplyr::select(-1)
May_merged_cleaned = cbind(May_merged_cleaned,
                      Slopes_eye =apply(X = May_merged_eyetemp, MARGIN= 1,
                                    FUN = find_slope))
formula3 = as.formula(paste("Slopes_eye ~", paste(colnames(May_merged_cleaned)[2:14],
                            collapse = " +"), sep = ""))
lm3 = lm(formula3, data = May_merged_cleaned)
print("May EYE Temperatures")
cooksd <- cooks.distance(lm3)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm3)
plot(stud_residuals)
shapiro.test(resid(lm3))
hist(resid(lm3))
table = summary(lm3)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC3 = stepAIC(lm3, trace = F, direction = "both")
print("May EYE Temperatures -- BEST SUBSET")
lrtest(lm3, lm(Slopes_eye ~., data = AIC3$model))
table = summary(lm(Slopes_eye ~., data = AIC3$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
##
May_merged_mouthtemp = May_merged_cleaned %>% dplyr::select(starts_with("Mac.Mouth"))%>%
  dplyr::select(-1)
May_merged_cleaned = cbind(May_merged_cleaned,
                      Slopes_mouth =apply(X = May_merged_mouthtemp, MARGIN= 1,
                                    FUN = find_slope))
formula4 = as.formula(paste("Slopes_mouth ~", paste(colnames(May_merged_cleaned)[2:14],collapse = " +"), sep = ""))
lm4 = lm(formula4, data = May_merged_cleaned)
print("May MOUTH Temperatures")
cooksd <- cooks.distance(lm4)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm4)
plot(stud_residuals)
shapiro.test(resid(lm4))
hist(resid(lm4))
table = summary(lm4)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC4 = stepAIC(lm4, trace = F, direction = "both")
print("May MOUTH Temperatures -- BEST SUBSET")
lrtest(lm4, lm(Slopes_mouth ~., data = AIC4$model))
table = summary(lm(Slopes_mouth ~., data = AIC4$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
```


```{r ND data, echo =F}
#ND_ear = read_xlsx("November-December trials/November-December dog thermal relations trials (ear temps).xlsx")
#ND_ear = ND_ear[-c(59:151),]
#ND_regular = read_xlsx("November-December trials/November Trials Regular Imaging.xlsx")
#ND_thermal = read_xlsx("November-December trials/November trials thermal imaging data.xlsx", sheet = 2)
#ND_merged = merge(ND_ear, ND_regular, by = c("Dog's Name"))
#ND_merged = merge(ND_merged, ND_thermal, by = c("Dog's Name"))
#ND_merged = write.csv(ND_merged, "merged_ND.csv")

##
####
ND_merged_cleaned = read_xlsx("November-December trials/merged_ND_2.xlsx", sheet = 2)
colnames(ND_merged_cleaned)[2:14] = gsub(" ", "_",colnames(ND_merged_cleaned)[2:14])
colnames(ND_merged_cleaned) = gsub(".x", "",colnames(ND_merged_cleaned))
colnames(ND_merged_cleaned) = gsub("\\(", "",colnames(ND_merged_cleaned))
colnames(ND_merged_cleaned) = gsub("\\)", "",colnames(ND_merged_cleaned))
colnames(ND_merged_cleaned) = gsub(",", "",colnames(ND_merged_cleaned))
ND_merged_cleaned$ear_length_in = in_to_cm(ND_merged_cleaned$ear_length_in)
ND_merged_cleaned$Front_leg_height_to_shoulder_in = in_to_cm(ND_merged_cleaned$Front_leg_height_to_shoulder_in)
ND_merged_cleaned$weight_lbs = ND_merged_cleaned$weight_lbs / 2.205
colnames(ND_merged_cleaned)[10:11] = gsub("_in", "",colnames(ND_merged_cleaned)[10:11])
ND_merged_cleaned[15:18] = f.to.c(ND_merged_cleaned[15:18])
ND_merged_cleaned = imputeapply(ND_merged_cleaned)

ND_merged_cleaned$Standardized_breed = as.factor(ND_merged_cleaned$Standardized_breed)
ND_merged_cleaned <- within(ND_merged_cleaned, 
                            Standardized_breed <- relevel(Standardized_breed, ref = "Mix"))

ND_merged_eartemp = ND_merged_cleaned %>% dplyr::select(starts_with("Tear"))%>%
  dplyr::select(-1)
ND_merged_cleaned = cbind(ND_merged_cleaned,
                      Slopes_ear =apply(X = ND_merged_eartemp, MARGIN= 1,
                                    FUN = find_slope))

formula1 = as.formula(paste("Slopes_ear ~", paste(colnames(ND_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
lm1 = lm(formula1, data = ND_merged_cleaned)
print("WINTER EAR Temperatures")
cooksd <- cooks.distance(lm1)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm1)
plot(stud_residuals)
shapiro.test(resid(lm1))
hist(resid(lm1))
table = summary(lm1)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC1 = stepAIC(lm1, trace = F, direction = "both")
print("WINTER EAR Temperatures -- BEST SUBSET")
lrtest(lm1, lm(Slopes_ear ~., data = AIC1$model))
table = summary(lm(Slopes_ear ~., data = AIC1$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
##
ND_merged_nosetemp = ND_merged_cleaned %>% dplyr::select(starts_with("M.Nose"))%>%
  dplyr::select(-1)
ND_merged_cleaned = cbind(ND_merged_cleaned,
                      Slopes_nose =apply(X = ND_merged_nosetemp, MARGIN= 1,
                                    FUN = find_slope))

formula2 = as.formula(paste("Slopes_nose ~", paste(colnames(ND_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
lm2 = lm(formula2, data = ND_merged_cleaned)
cooksd <- cooks.distance(lm2)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm2)
plot(stud_residuals)
shapiro.test(resid(lm2))
hist(resid(lm2))
print("WINTER NOSE Temperatures")
table = summary(lm2)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC2 = stepAIC(lm2, trace = F, direction = "both")
print("WINTER NOSE Temperatures -- BEST SUBSET")
lrtest(lm2, lm(Slopes_nose~., data = AIC2$model))
table = summary(lm(Slopes_nose~., data = AIC2$model))
#table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
##
ND_merged_eyetemp = ND_merged_cleaned %>% dplyr::select(starts_with("M.Eye"))%>%
  dplyr::select(-1)
ND_merged_cleaned = cbind(ND_merged_cleaned,
                      Slopes_eye =apply(X = ND_merged_eyetemp, MARGIN= 1,
                                    FUN = find_slope))

formula3 = as.formula(paste("Slopes_eye ~", paste(colnames(ND_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
lm3 = lm(formula3, data = ND_merged_cleaned)
print("WINTER EYE Temperatures")
cooksd <- cooks.distance(lm3)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm3)
plot(stud_residuals)
shapiro.test(resid(lm3))
hist(resid(lm3))
table = summary(lm3)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC3 = stepAIC(lm3, trace = F, direction = "both")
print("WINTER EYE Temperatures -- BEST SUBSET")
lrtest(lm3, lm(Slopes_eye~., data = AIC3$model))
table = summary(lm(Slopes_eye~., data = AIC3$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
##
ND_merged_mouthtemp = ND_merged_cleaned %>% dplyr::select(starts_with("Mac.Mouth"))%>%
  dplyr::select(-1)
ND_merged_cleaned = cbind(ND_merged_cleaned,
                      Slopes_mouth =apply(X = ND_merged_mouthtemp, MARGIN= 1,
                                    FUN = find_slope))

formula4 = as.formula(paste("Slopes_mouth ~", paste(colnames(ND_merged_cleaned)[2:14], 
                            collapse = " +"), sep = ""))
lm4 = lm(formula4, data = ND_merged_cleaned)
print("WINTER MOUTH Temperatures")
cooksd <- cooks.distance(lm4)
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 1, col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>1, names(cooksd),""), col="red")
stud_residuals = studres(lm4)
plot(stud_residuals)
shapiro.test(resid(lm4))
hist(resid(lm4))
table = summary(lm4)
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
AIC4 = stepAIC(lm4, trace = F, direction = "both")
print("WINTER MOUTH Temperatures -- BEST SUBSET")
lrtest(lm4, lm(Slopes_mouth~., data = AIC4$model))
table = summary(lm(Slopes_mouth~., data = AIC4$model))
table$coefficients[,4] = p.adjust(table$coefficients[,4], method= "BH")
table
```

Between Seasons Analysis
```{r Interseason, warning=F, message=F,echo=F, include=T}

library(lmerTest)
library(lqmm)
library(PMCMR)
##### DO NOT RUN THIS MORE THAN ONCE
ND_merged_cleaned$Ta.begin.F = f.to.c(ND_merged_cleaned$Ta.begin.F)
ND_merged_cleaned$Ta.end.F = f.to.c(ND_merged_cleaned$Ta.end.F)
ND_merged_cleaned$Humidity.begin = ND_merged_cleaned$Humidity.begin * 100
ND_merged_cleaned$Humidity.end = ND_merged_cleaned$Humidity.end * 100

JJ_merged_cleaned$JJ_ta_avg = (JJ_merged_cleaned$`Ta begin C ` + JJ_merged_cleaned$`Ta end C `)/2
May_merged_cleaned$May_ta_avg = (May_merged_cleaned$Ta.begin.C + May_merged_cleaned$Ta.end.C)/2
ND_merged_cleaned$ND_ta_avg = (ND_merged_cleaned$Ta.begin.F + ND_merged_cleaned$Ta.end.F)/2

JJ_merged_cleaned$JJ_humid_avg = (JJ_merged_cleaned$`Humidity begin` + JJ_merged_cleaned$`Humidity end`)/2
May_merged_cleaned$May_humid_avg = (May_merged_cleaned$Humidity.begin. + May_merged_cleaned$Humidity.end..)/2
ND_merged_cleaned$ND_humid_avg = (ND_merged_cleaned$Humidity.begin + ND_merged_cleaned$Humidity.end)/2

#####
colnames(JJ_merged_cleaned)[1] = "Dog"
interseason = JJ_merged_cleaned %>% dplyr::select(c(1,35:40))
colnames(interseason)[2:5] = paste0("JJ_",colnames(interseason)[2:5])
colnames(May_merged_cleaned)[1] = "Dog"
interseason = merge(interseason, May_merged_cleaned %>% dplyr::select(c(1, 35:40)), by = "Dog")
colnames(interseason)[8:11] = paste0("May_",colnames(interseason)[8:11])
colnames(ND_merged_cleaned)[1] = "Dog"
interseason = merge(interseason, ND_merged_cleaned %>% dplyr::select(c(1, 35:40)), by = "Dog")
colnames(interseason)[14:17] = paste0("ND_",colnames(interseason)[14:17])

#interseason = interseason[-c(which(interseason$Dog == "Murphy")),]
print("RM-ANOVA Ear")
anova.dat_ear = interseason %>% dplyr::select(c("Dog", ends_with("_ear")))

anova.dat_ear = anova.dat_ear %>% pivot_longer(cols = -c("Dog"),
                                               names_to = "Season",
                                              values_to = "Slopes") 
ezANOVA(data = anova.dat_ear, dv = (Slopes), wid = Dog , within = Season)

print("RM-ANOVA Eye")
anova.dat_eye = interseason %>% dplyr::select(c("Dog", ends_with("_eye")))

anova.dat_eye = anova.dat_eye %>% pivot_longer(cols = -c("Dog"),
                                               names_to = "Season",
                                              values_to = "Slopes") 
ezANOVA(data = anova.dat_eye, dv = (Slopes), wid = Dog , within = Season)

anova.dat_nose = interseason %>% dplyr::select(c("Dog", ends_with("_nose")))
anova.dat_nose = anova.dat_nose %>% pivot_longer(cols = -c("Dog"),
                                               names_to = "Season",
                                              values_to = "Slopes") 
print("RM-ANOVA Nose")
ezANOVA(data = anova.dat_nose, dv = (Slopes), wid = Dog , within = Season)


anova.dat_mouth = interseason %>% dplyr::select(c("Dog", ends_with("_mouth")))
anova.dat_mouth = anova.dat_mouth %>% pivot_longer(cols = -c("Dog"),
                                               names_to = "Season",
                                              values_to = "Slopes") 
print("RM-ANOVA Mouth")
ezANOVA(data = anova.dat_mouth, dv = (Slopes), wid = Dog , within = Season)

#####
# MIXED EFFECT MODELS

mixed.dat_ear = interseason %>% dplyr::select(c("Dog", ends_with("_ear"), ends_with("_avg")))
mixed.dat_ear_2 = data.frame(Slopes = rep(NA,132))
mixed.dat_ear_2$Slopes = c(mixed.dat_ear$JJ_Slopes_ear, mixed.dat_ear$May_Slopes_ear, mixed.dat_ear$ND_Slopes_ear)

mixed.dat_ear_2$Ta = c(mixed.dat_ear$JJ_ta_avg, mixed.dat_ear$May_ta_avg, mixed.dat_ear$ND_ta_avg)
mixed.dat_ear_2$Humid = c(mixed.dat_ear$JJ_humid_avg, mixed.dat_ear$May_humid_avg, mixed.dat_ear$ND_humid_avg)
mixed.dat_ear_2$Season = c(rep("JJ", 44), rep("May", 44), rep("ND",44))
mixed.dat_ear_2$Dog = c(rep(interseason$Dog,3))

print("Mixed Effects Model -- Ear")
table = summary(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_ear_2))
#table$coefficients[,5] = p.adjust(table$coefficients[,5], method= "BH")
table
#hist(resid(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_ear_2)))
#summary(lqmm(Slopes ~ Ta * Humid, random = ~1,group = Dog,data = mixed.dat_ear_2))

##
mixed.dat_eye = interseason %>% dplyr::select(c("Dog", ends_with("_eye"), ends_with("_avg")))
mixed.dat_eye_2 = data.frame(Slopes = rep(NA,132))
mixed.dat_eye_2$Slopes = c(mixed.dat_eye$JJ_Slopes_eye, mixed.dat_eye$May_Slopes_eye, mixed.dat_eye$ND_Slopes_eye)

mixed.dat_eye_2$Ta = c(mixed.dat_eye$JJ_ta_avg, mixed.dat_eye$May_ta_avg, mixed.dat_eye$ND_ta_avg)
mixed.dat_eye_2$Humid = c(mixed.dat_eye$JJ_humid_avg, mixed.dat_eye$May_humid_avg, mixed.dat_eye$ND_humid_avg)
mixed.dat_eye_2$Season = c(rep("JJ", 44), rep("May", 44), rep("ND",44))
mixed.dat_eye_2$Dog = c(rep(interseason$Dog,3))

print("Mixed Effects Model -- Eye")
table = summary(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_eye_2))
#table$coefficients[,5] = p.adjust(table$coefficients[,5], method= "BH")
table
#hist(resid(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_eye_2)))
#summary(lqmm(Slopes ~ Ta * Humid, random = ~1,group = Dog,data = mixed.dat_eye_2))

##

mixed.dat_nose = interseason %>% dplyr::select(c("Dog", ends_with("_nose"), ends_with("_avg")))
mixed.dat_nose_2 = data.frame(Slopes = rep(NA,132))
mixed.dat_nose_2$Slopes = c(mixed.dat_nose$JJ_Slopes_nose, mixed.dat_nose$May_Slopes_nose, mixed.dat_nose$ND_Slopes_nose)

mixed.dat_nose_2$Ta = c(mixed.dat_nose$JJ_ta_avg, mixed.dat_nose$May_ta_avg, mixed.dat_nose$ND_ta_avg)
mixed.dat_nose_2$Humid = c(mixed.dat_nose$JJ_humid_avg, mixed.dat_nose$May_humid_avg, mixed.dat_nose$ND_humid_avg)
mixed.dat_nose_2$Season = c(rep("JJ", 44), rep("May", 44), rep("ND",44))
mixed.dat_nose_2$Dog = c(rep(interseason$Dog,3))

print("Mixed Effects Model -- Nose")
table = summary(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_nose_2))
#table$coefficients[,5] = p.adjust(table$coefficients[,5], method= "BH")
table
#which(resid(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_nose_2)) > 10)
# cooksd <- cooks.distance(lmerTest::lmer(Slopes ~ Ta + Humid + (1| Dog), data = mixed.dat_nose_2))
# plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
# abline(h = 4/44, col="red")  # add cutoff line
# text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>4/44, names(cooksd),""), col="red")
#summary(lqmm(Slopes ~ Ta * Humid, random = ~1,group = Dog,data = mixed.dat_nose_2))

##
mixed.dat_mouth = interseason %>% dplyr::select(c("Dog", ends_with("_mouth"), ends_with("_avg")))
mixed.dat_mouth_2 = data.frame(Slopes = rep(NA,132))
mixed.dat_mouth_2$Slopes = c(mixed.dat_mouth$JJ_Slopes_mouth, mixed.dat_mouth$May_Slopes_mouth, mixed.dat_mouth$ND_Slopes_mouth)

mixed.dat_mouth_2$Ta = c(mixed.dat_mouth$JJ_ta_avg, mixed.dat_mouth$May_ta_avg, mixed.dat_mouth$ND_ta_avg)
mixed.dat_mouth_2$Humid = c(mixed.dat_mouth$JJ_humid_avg, mixed.dat_mouth$May_humid_avg, mixed.dat_mouth$ND_humid_avg)
mixed.dat_mouth_2$Season = c(rep("JJ", 44), rep("May", 44), rep("ND",44))
mixed.dat_mouth_2$Dog = c(rep(interseason$Dog,3))

print("Mixed Effects Model -- Mouth")
table = summary(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_mouth_2))
#table$coefficients[,5] = p.adjust(table$coefficients[,5], method= "BH")
table
#which(resid(lmerTest::lmer(Slopes ~ Ta * Humid + (1| Dog), data = mixed.dat_nose_2)) >10)
#summary(lqmm(Slopes ~ Ta * Humid, random = ~1,group = Dog,data = mixed.dat_mouth_2))
```

```{r Networks, warning=F, message=F, echo=F}
library(minet)
library(Rgraphviz)
library(igraph)
library(dplyr)
library(psych)
## May
May_cont = May_merged_cleaned %>% dplyr::select(c(1:14, "Slopes_ear", "Slopes_mouth","Slopes_eye","Slopes_nose")) %>% dplyr::filter(Dog %in% mixed.dat_ear_2$Dog)
May_cont$Gender = if_else(May_cont$Gender == "M", 1,0)
May_cont = May_cont %>% dplyr::select(-c("Dog"))
new_mim = matrix(rep(0, 17*17), nrow = 17)
colnames(new_mim) =c("Breed", "Body Mass", "Coat Color", "Coat Type",
                      "Ear Morphology", "Sex", "Age","Coat Length",
                      "Nose Length", "Ear Length","Leg Length",
                      "Snout Length", "Paw Width", "Ear Temperature",
                      "Mouth Temperature", "Eye Temperature","Nose Temperature")
rownames(new_mim) =colnames(new_mim)
for (i in 1:100){
  set.seed(i)
  index = sample(1:nrow(May_cont), size=nrow(May_cont), replace = T)
  data = May_cont[index,]
  mim <- build.mim(data, disc = "equalfreq", estimator="mi.empirical")
  mim[mim < 0.5] = 0
  for (j in (1:ncol(mim)) ){
    for (k in (1:ncol(mim)) ){
      if (mim[j,k] > 0) {
        new_mim[j,k] = new_mim[j,k]+1
      }
    }
  }
}
new_mim[new_mim<95] = 0
May_mim = new_mim
new_mim = new_mim[colSums(new_mim) !=0,colSums(new_mim) !=0]
nodeLabels =colnames(new_mim)
names(nodeLabels)<-colnames(new_mim)
nAttrs = list()
nAttrs$label<-nodeLabels
attrs <- list(node = list(shape = "ellipse", fixedsize = F))
attrs$node$fontsize<-15
attrs$node$size<-20
tiff("network_May.tiff", width =5, height =5,
         units = "in", res =300)
plot( as( new_mim ,"graphNEL"),nodeAttrs = nAttrs, attrs = attrs,cex.sub = 1.5)
dev.off()

graph = igraph::graph_from_adjacency_matrix(new_mim, mode = "undirected", diag =F,weighted = T)
May_metric_1 = betweenness(graph)
May_metric_2 = degree(graph)
May_metric_3 = closeness(graph, mode ="all")
May_metric_4 = transitivity(graph, type = "global")
May_metric_5 = vertex_connectivity(graph)
# plot(graph, layout = layout.graphopt(graph),
#          normalize = F,
#          edge.arrow.mode = 0,
#          vertex.label.cex = 1.6, vertex.label.font = 2, vertex.label.color= "black"
#          , cex = 3)

## JJ
JJ_cont = JJ_merged_cleaned %>% dplyr::select(c(1:14, "Slopes_ear", "Slopes_mouth","Slopes_eye","Slopes_nose")) %>% dplyr::filter(Dog %in% mixed.dat_ear_2$Dog)
JJ_cont$Gender = if_else(JJ_cont$Gender == "M", 1,0)
JJ_cont = JJ_cont %>% dplyr::select(-c("Dog"))
new_mim = matrix(rep(0, 17*17), nrow = 17)
colnames(new_mim) =c("Breed", "Body Mass", "Coat Color", "Coat Type",
                      "Ear Morphology", "Sex", "Age","Coat Length",
                      "Nose Length", "Ear Length","Leg Length",
                      "Snout Length", "Paw Width", "Ear Temperature",
                      "Mouth Temperature", "Eye Temperature","Nose Temperature")
rownames(new_mim) =colnames(new_mim)
for (i in 1:100){
  set.seed(i)
  index = sample(1:nrow(JJ_cont), size=nrow(JJ_cont), replace = T)
  data = JJ_cont[index,]
  mim <- build.mim(data, disc = "equalfreq", estimator="mi.empirical")
  mim[mim < 0.5] = 0
  for (j in (1:ncol(mim)) ){
    for (k in (1:ncol(mim)) ){
      if (mim[j,k] > 0) {
        new_mim[j,k] = new_mim[j,k]+1
      }
    }
  }
}
new_mim[new_mim<95] = 0
JJ_mim = new_mim
new_mim = new_mim[colSums(new_mim) !=0,colSums(new_mim) !=0]
nodeLabels =colnames(new_mim)
names(nodeLabels)<-colnames(new_mim)
nAttrs = list()
nAttrs$label<-nodeLabels
attrs <- list(node = list(shape = "ellipse", fixedsize = F))
attrs$node$fontsize<-15
attrs$node$size<-20
tiff("network_JJ.tiff", width =5, height =5,
         units = "in", res =300)
plot( as( new_mim ,"graphNEL"),nodeAttrs = nAttrs, attrs = attrs,cex.sub = 1.5)
dev.off()
graph = igraph::graph_from_adjacency_matrix(new_mim, mode = "undirected", diag =F,weighted = T)
JJ_metric_1 = betweenness(graph)
JJ_metric_2 = degree(graph)
JJ_metric_3 = closeness(graph, mode ="all")
JJ_metric_4 = transitivity(graph, type = "global")
JJ_metric_5 = vertex_connectivity(graph)

## ND
colnames(ND_merged_cleaned)[1] = "Dog"
ND_cont = ND_merged_cleaned %>% dplyr::select(c(1:14, "Slopes_ear", "Slopes_mouth","Slopes_eye","Slopes_nose")) %>% dplyr::filter(Dog %in% mixed.dat_ear_2$Dog)
ND_cont$Gender = if_else(ND_cont$Gender == "M", 1,0)
ND_cont = ND_cont %>% dplyr::select(-c("Dog"))
new_mim = matrix(rep(0, 17*17), nrow = 17)
colnames(new_mim) =c("Breed", "Body Mass", "Coat Color", "Coat Type",
                      "Ear Morphology", "Sex", "Age","Coat Length",
                      "Nose Length", "Ear Length","Leg Length",
                      "Snout Length", "Paw Width", "Ear Temperature",
                      "Mouth Temperature", "Eye Temperature","Nose Temperature")
rownames(new_mim) =colnames(new_mim)
for (i in 1:100){
  set.seed(i)
  index = sample(1:nrow(ND_cont), size=nrow(ND_cont), replace = T)
  data = ND_cont[index,]
  mim <- build.mim(data, disc = "equalfreq", estimator="mi.empirical")
  mim[mim < 0.5] = 0
  for (j in (1:ncol(mim)) ){
    for (k in (1:ncol(mim)) ){
      if (mim[j,k] > 0) {
        new_mim[j,k] = new_mim[j,k]+1
      }
    }
  }
}
new_mim[new_mim<95] = 0
ND_mim = new_mim
new_mim = new_mim[colSums(new_mim) !=0,colSums(new_mim) !=0]
nodeLabels =colnames(new_mim)
names(nodeLabels)<-colnames(new_mim)
nAttrs = list()
nAttrs$label<-nodeLabels
attrs <- list(node = list(shape = "ellipse", fixedsize = F))
attrs$node$fontsize<-15
attrs$node$size<-20
tiff("network_ND.tiff", width =5, height =5,
         units = "in", res =300)
plot( as( new_mim ,"graphNEL"),nodeAttrs = nAttrs, attrs = attrs,cex.sub = 1.5)
dev.off()

graph = igraph::graph_from_adjacency_matrix(new_mim, mode = "undirected", diag =F,weighted = T)
ND_metric_1 = betweenness(graph)
ND_metric_2 = degree(graph)
ND_metric_3 = closeness(graph, mode ="all")
ND_metric_4 = transitivity(graph, type = "global")
ND_metric_5 = vertex_connectivity(graph)

union_mim = May_mim + JJ_mim + ND_mim
union_mim[union_mim>0] = 0
for (i in 1:nrow(union_mim)){
  for (j in 1:nrow(union_mim)){
    if (May_mim[i,j] >0){
      union_mim[i,j] = "Sp"
    }
    if (JJ_mim[i,j] >0){
      union_mim[i,j] = paste(union_mim[i,j], ",Su", sep = "")
    }
    if (ND_mim[i,j] >0){
      union_mim[i,j] =paste(union_mim[i,j], ",Wi", sep = "")
    }
  }
}
write.csv(union_mim, file = "adj.mat.csv")

```

Mediation Analysis.
```{r Mediation, message=F, echo=F, warning=F, results = 'hide', eval =F}
library(mediation)
sink("Mediation.txt", type = "output")
set.seed(123)

summary(mediate(lm(Nose_length ~ weight_in_kg+Snout_length+Right_leg_length, data = May_merged_cleaned), lm(Slopes_mouth ~ Nose_length + weight_in_kg+Snout_length+Right_leg_length, data = May_merged_cleaned), sims = 1000, boot = T, treat = "weight_in_kg", mediator = "Nose_length"))

summary(mediate(lm(Snout_length ~ weight_in_kg + Right_leg_length+Nose_length, data = May_merged_cleaned), lm(Slopes_mouth ~ Nose_length + weight_in_kg+Snout_length+Right_leg_length, data = May_merged_cleaned), sims = 1000, boot = T, treat = "weight_in_kg", mediator = "Snout_length"))

summary(mediate(lm(Right_leg_length ~ weight_in_kg +Snout_length+Nose_length, data = May_merged_cleaned), lm(Slopes_mouth ~ Nose_length + weight_in_kg+Snout_length+Right_leg_length, data = May_merged_cleaned), sims = 1000, boot = T, treat = "weight_in_kg", mediator = "Right_leg_length"))


summary(mediate(lm(ear_length ~ weight_in_kg, data = May_merged_cleaned), lm(Slopes_eye ~ ear_length + weight_in_kg, data = May_merged_cleaned), sims = 1000, boot = T, treat = "weight_in_kg", mediator = "ear_length"))


summary(mediate(lm(Nose_length ~ weight_in_kg, data = JJ_merged_cleaned), lm(Slopes_mouth ~ weight_in_kg +Nose_length + Paw_width_cm, data = JJ_merged_cleaned), sims = 1000, boot = T, treat = "weight_in_kg", mediator = "Nose_length"))

summary(mediate(lm(Paw_width_cm ~ weight_in_kg, data = JJ_merged_cleaned), lm(Slopes_mouth ~ weight_in_kg +Paw_width_cm + Nose_length, data = JJ_merged_cleaned), sims = 1000, boot = T, treat = "weight_in_kg", mediator = "Paw_width_cm"))


summary(mediate(lm(Nose_length ~ weight_in_kg+Coat_length_cm+Paw_width_cm, data = JJ_merged_cleaned),lm(Slopes_nose~Nose_length+weight_in_kg+Coat_length_cm+Paw_width_cm, data= JJ_merged_cleaned),
                boot =T, sims =1000, treat = "weight_in_kg", mediator = "Nose_length"))

summary(mediate(lm(Paw_width_cm ~ weight_in_kg+ Coat_length_cm+Nose_length, data = JJ_merged_cleaned),lm(Slopes_nose~Nose_length+weight_in_kg+Coat_length_cm+Paw_width_cm, data= JJ_merged_cleaned),
                boot =T, sims =1000, treat = "weight_in_kg", mediator = "Paw_width_cm"))

summary(mediate(lm(Coat_length_cm ~ weight_in_kg + Paw_width_cm + Nose_length, data = JJ_merged_cleaned),lm(Slopes_nose~Nose_length+weight_in_kg+Coat_length_cm+Paw_width_cm, data= JJ_merged_cleaned),
                boot =T, sims =1000, treat = "weight_in_kg", mediator = "Coat_length_cm"))



summary(mediate(lm(Nose_length ~ weight_in_kg, data = JJ_merged_cleaned), lm(Slopes_ear~ Nose_length + weight_in_kg, data = JJ_merged_cleaned), sims = 1000, boot = T, treat = "weight_in_kg", mediator = "Nose_length"))



summary(mediate(lm(ear_length ~ weight_lbs ,data = ND_merged_cleaned), lm(Slopes_nose ~ ear_length + weight_lbs, data = ND_merged_cleaned), sims = 1000, boot = T, mediator = "ear_length", treat = "weight_lbs"))




sink()
p.adjust(c(0.018,0.024,0.50),method = "BH")
p.adjust(c(0.028, 0.02), method ="BH")
p.adjust(c(0.178,0.062,0.046), method = "BH")


```

```{r Plotting Grouped, message=F, warning=F, echo=F}
summary_tab_ear = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),3))


summary_tab_ear$Average = rep(NA,12)
summary_tab_ear$SE = rep(NA,12)
summary_tab_ear$Season = c(rep("Spring",4), rep("Summer",4), rep("Winter",4))

summary_tab_ear = summary_tab_ear  %>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))
summary_tab_ear[1:4,2]= c(mean(May_merged_cleaned[,15]),
                                 mean(May_merged_cleaned[,16]),
                                 mean(May_merged_cleaned[,17]),
                                 mean(May_merged_cleaned[,18]))
summary_tab_ear[5:8,2]= c(mean(JJ_merged_cleaned[,15]),
                                 mean(JJ_merged_cleaned[,16]),
                                 mean(JJ_merged_cleaned[,17]),
                                 mean(JJ_merged_cleaned[,18]))
summary_tab_ear[9:12,2]= c(mean(ND_merged_cleaned[,15]),
                                 mean(ND_merged_cleaned[,16]),
                                 mean(ND_merged_cleaned[,17]),
                                 mean(ND_merged_cleaned[,18]))
summary_tab_ear[1:4,3]= c(se(May_merged_cleaned[,15]),
                                 se(May_merged_cleaned[,16]),
                                 se(May_merged_cleaned[,17]),
                                 se(May_merged_cleaned[,18]))
summary_tab_ear[5:8,3]= c(se(JJ_merged_cleaned[,15]),
                                 se(JJ_merged_cleaned[,16]),
                                 se(JJ_merged_cleaned[,17]),
                                 se(JJ_merged_cleaned[,18]))
summary_tab_ear[9:12,3]= c(se(ND_merged_cleaned[,15]),
                                 se(ND_merged_cleaned[,16]),
                                 se(ND_merged_cleaned[,17]),
                                 se(ND_merged_cleaned[,18]))


tiff("Plot_ear.tiff",
     width =8.7, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_ear, aes(x = TimePoint, y = Average, colour = Season)) + 
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['ear']*~(degree*C)))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  ylim(36,40)+
  theme(
      axis.text=element_text(size=28), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.position = c(.864, .902),
      legend.key.width= unit(1.1, 'cm'),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"))
dev.off()



#####

summary_tab_mouth = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),3))


summary_tab_mouth$Average = rep(NA,12)
summary_tab_mouth$SE = rep(NA,12)
summary_tab_mouth$Season = c(rep("Spring",4), rep("Summer",4), rep("Winter",4))

summary_tab_mouth = summary_tab_mouth  %>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))
summary_tab_mouth[1:4,2]= c(mean(May_merged_cleaned[,21]),
                                 mean(May_merged_cleaned[,24]),
                                 mean(May_merged_cleaned[,27]),
                                 mean(May_merged_cleaned[,30]))
summary_tab_mouth[5:8,2]= c(mean(JJ_merged_cleaned[,21]),
                                 mean(JJ_merged_cleaned[,24]),
                                 mean(JJ_merged_cleaned[,27]),
                                 mean(JJ_merged_cleaned[,30]))
summary_tab_mouth[9:12,2]= c(mean(ND_merged_cleaned[,21]),
                                 mean(ND_merged_cleaned[,24]),
                                 mean(ND_merged_cleaned[,27]),
                                 mean(ND_merged_cleaned[,30]))
summary_tab_mouth[1:4,3]= c(se(May_merged_cleaned[,21]),
                                 se(May_merged_cleaned[,24]),
                                 se(May_merged_cleaned[,27]),
                                 se(May_merged_cleaned[,30]))
summary_tab_mouth[5:8,3]= c(se(JJ_merged_cleaned[,21]),
                                 se(JJ_merged_cleaned[,24]),
                                 se(JJ_merged_cleaned[,27]),
                                 se(JJ_merged_cleaned[,30]))
summary_tab_mouth[9:12,3]= c(se(ND_merged_cleaned[,21]),
                                 se(ND_merged_cleaned[,24]),
                                 se(ND_merged_cleaned[,27]),
                                 se(ND_merged_cleaned[,30]))


tiff("Plot_mouth.tiff",
     width =8.7, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_mouth, aes(x = TimePoint, y = Average, colour = Season)) + 
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['mouth']*~(degree*C)))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  ylim(20,40)+
  theme(
      axis.text=element_text(size=28), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.key.width= unit(1.1, 'cm'),
      legend.position = c(.87, .902),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"))
dev.off()


#####

summary_tab_nose = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),3))


summary_tab_nose$Average = rep(NA,12)
summary_tab_nose$SE = rep(NA,12)
summary_tab_nose$Season = c(rep("Spring",4), rep("Summer",4), rep("Winter",4))

summary_tab_nose = summary_tab_nose  %>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))
summary_tab_nose[1:4,2]= c(mean(May_merged_cleaned[,19]),
                                 mean(May_merged_cleaned[,22]),
                                 mean(May_merged_cleaned[,25]),
                                 mean(May_merged_cleaned[,28]))
summary_tab_nose[5:8,2]= c(mean(JJ_merged_cleaned[,19]),
                                 mean(JJ_merged_cleaned[,22]),
                                 mean(JJ_merged_cleaned[,25]),
                                 mean(JJ_merged_cleaned[,28]))
summary_tab_nose[9:12,2]= c(mean(ND_merged_cleaned[,19]),
                                 mean(ND_merged_cleaned[,22]),
                                 mean(ND_merged_cleaned[,25]),
                                 mean(ND_merged_cleaned[,28]))
summary_tab_nose[1:4,3]= c(se(May_merged_cleaned[,19]),
                                 se(May_merged_cleaned[,22]),
                                 se(May_merged_cleaned[,25]),
                                 se(May_merged_cleaned[,28]))
summary_tab_nose[5:8,3]= c(se(JJ_merged_cleaned[,19]),
                                 se(JJ_merged_cleaned[,22]),
                                 se(JJ_merged_cleaned[,25]),
                                 se(JJ_merged_cleaned[,28]))
summary_tab_nose[9:12,3]= c(se(ND_merged_cleaned[,19]),
                                 se(ND_merged_cleaned[,22]),
                                 se(ND_merged_cleaned[,25]),
                                 se(ND_merged_cleaned[,28]))


tiff("Plot_nose.tiff",
     width =8.7, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_nose, aes(x = TimePoint, y = Average, colour = Season)) + 
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['nose']*(~degree*C)))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  ylim(18,40)+
  theme(
      axis.text=element_text(size=28), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.position = c(.869, .902),
      legend.key.width= unit(1.1, 'cm'),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"))
dev.off()


#####

summary_tab_eye = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),3))


summary_tab_eye$Average = rep(NA,12)
summary_tab_eye$SE = rep(NA,12)
summary_tab_eye$Season = c(rep("Spring",4), rep("Summer",4), rep("Winter",4))

summary_tab_eye = summary_tab_eye %>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))

summary_tab_eye[1:4,2]= c(mean(May_merged_cleaned[,20]),
                                 mean(May_merged_cleaned[,23]),
                                 mean(May_merged_cleaned[,26]),
                                 mean(May_merged_cleaned[,29]))
summary_tab_eye[5:8,2]= c(mean(JJ_merged_cleaned[,20]),
                                 mean(JJ_merged_cleaned[,23]),
                                 mean(JJ_merged_cleaned[,26]),
                                 mean(JJ_merged_cleaned[,29]))
summary_tab_eye[9:12,2]= c(mean(ND_merged_cleaned[,20]),
                                 mean(ND_merged_cleaned[,23]),
                                 mean(ND_merged_cleaned[,26]),
                                 mean(ND_merged_cleaned[,29]))
summary_tab_eye[1:4,3]= c(se(May_merged_cleaned[,20]),
                                 se(May_merged_cleaned[,23]),
                                 se(May_merged_cleaned[,26]),
                                 se(May_merged_cleaned[,29]))
summary_tab_eye[5:8,3]= c(se(JJ_merged_cleaned[,20]),
                                 se(JJ_merged_cleaned[,23]),
                                 se(JJ_merged_cleaned[,26]),
                                 se(JJ_merged_cleaned[,29]))
summary_tab_eye[9:12,3]= c(se(ND_merged_cleaned[,20]),
                                 se(ND_merged_cleaned[,23]),
                                 se(ND_merged_cleaned[,26]),
                                 se(ND_merged_cleaned[,29]))


tiff("Plot_eye.tiff",
     width =8.7, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_eye, aes(x = TimePoint, y = Average, colour = Season)) + 
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['eye']*~(degree*C) ))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  guides(linetype = guide_legend(override.aes = list(size = 3)))+
  ylim(25,40)+
  theme(
      axis.text=element_text(size=28), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.key.width= unit(1.1, 'cm'),
      legend.position = c(.868, .902),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"))
dev.off()
```

```{r Plotting Trends, message=F, warning=F, echo=F}
summary_tab_ear_2 = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),6))


summary_tab_ear_2$Average = rep(NA,24)
summary_tab_ear_2$SE = rep(NA,24)
summary_tab_ear_2$Season = c(rep("Spring",8), rep("Summer",8), rep("Winter",8))
summary_tab_ear_2$Trend = rep(c(rep("Increasing",4), rep("Decreasing",4)),3)

summary_tab_ear_2 = summary_tab_ear_2 %>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))

summary_tab_ear_2[1:4,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,15]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,16]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,17]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,18]))
summary_tab_ear_2[5:8,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,15]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,16]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,17]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,18]))

summary_tab_ear_2[9:12,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,15]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,16]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,17]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,18]))
summary_tab_ear_2[13:16,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,15]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,16]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,17]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,18]))
summary_tab_ear_2[17:20,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,15]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,16]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,17]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,18]))
summary_tab_ear_2[21:24,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,15]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,16]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,17]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,18]))

summary_tab_ear_2[1:4,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,15]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,16]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,17]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_ear>0,18]))
summary_tab_ear_2[5:8,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,15]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,16]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,17]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_ear<=0,18]))

summary_tab_ear_2[9:12,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,15]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,16]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,17]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear>0,18]))
summary_tab_ear_2[13:16,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,15]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,16]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,17]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_ear<=0,18]))
summary_tab_ear_2[17:20,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,15]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,16]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,17]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear>0,18]))
summary_tab_ear_2[21:24,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,15]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,16]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,17]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_ear<=0,18]))

tiff("Plot_ear_2.tiff",
     width =11, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_ear_2, aes(x = TimePoint, y = Average, colour = Season)) + 
  facet_wrap(~Trend)+
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['ear']*~(degree*C)))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  theme(
      axis.text=element_text(size=19), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.position = c(.902, 0.105),
      legend.key.width= unit(1.1, 'cm'),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"),
      strip.text.x = element_text(size = 30))
dev.off()



#####

summary_tab_mouth_2 = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),6))


summary_tab_mouth_2$Average = rep(NA,24)
summary_tab_mouth_2$SE = rep(NA,24)
summary_tab_mouth_2$Season = c(rep("Spring",8), rep("Summer",8), rep("Winter",8))
summary_tab_mouth_2 = summary_tab_mouth_2%>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))
summary_tab_mouth_2$Trend = rep(c(rep("Increasing",4), rep("Decreasing",4)),3)

summary_tab_mouth_2[1:4,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,21]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,24]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,27]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,30]))
summary_tab_mouth_2[5:8,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,21]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,24]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,27]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,30]))

summary_tab_mouth_2[9:12,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,21]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,24]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,27]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,30]))

summary_tab_mouth_2[13:24,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,21]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,24]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,27]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,30]))

summary_tab_mouth_2[17:20,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,21]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,24]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,27]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,30]))

summary_tab_mouth_2[21:24,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,21]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,24]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,27]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,30]))

summary_tab_mouth_2[1:4,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,21]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,24]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,27]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth>0,30]))
summary_tab_mouth_2[5:8,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,21]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,24]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,27]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_mouth<=0,30]))

summary_tab_mouth_2[9:12,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,21]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,24]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,27]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth>0,30]))
summary_tab_mouth_2[13:16,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,21]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,24]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,27]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_mouth<=0,30]))
summary_tab_mouth_2[17:20,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,21]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,24]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,27]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth>0,30]))
summary_tab_mouth_2[21:24,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,21]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,24]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,27]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_mouth<=0,30]))


tiff("Plot_mouth_2.tiff",
     width =11, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_mouth_2, aes(x = TimePoint, y = Average, colour = Season)) + 
  facet_wrap(~Trend)+
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['mouth']*~(degree*C)))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  theme(
      axis.text=element_text(size=19), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.key.width= unit(1.1, 'cm'),
      legend.position = c(.902, 0.105),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"),
      strip.text.x = element_text(size = 30))
dev.off()


#####

summary_tab_nose_2 = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),6))


summary_tab_nose_2$Average = rep(NA,24)
summary_tab_nose_2$SE = rep(NA,24)
summary_tab_nose_2$Season = c(rep("Spring",8), rep("Summer",8), rep("Winter",8))

summary_tab_nose_2 = summary_tab_nose_2 %>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))
summary_tab_nose_2$Trend = rep(c(rep("Increasing",4), rep("Decreasing",4)),3)

summary_tab_nose_2[1:4,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,19]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,22]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,25]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,28]))
summary_tab_nose_2[5:8,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,19]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,22]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,25]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,28]))

summary_tab_nose_2[9:12,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,19]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,22]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,25]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,28]))

summary_tab_nose_2[13:24,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,19]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,22]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,25]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,28]))

summary_tab_nose_2[17:20,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,19]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,22]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,25]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,28]))

summary_tab_nose_2[21:24,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,19]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,22]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,25]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,28]))

summary_tab_nose_2[1:4,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,19]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,22]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,25]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_nose>0,28]))
summary_tab_nose_2[5:8,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,19]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,22]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,25]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_nose<=0,28]))

summary_tab_nose_2[9:12,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,19]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,22]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,25]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose>0,28]))
summary_tab_nose_2[13:16,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,19]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,22]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,25]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_nose<=0,28]))
summary_tab_nose_2[17:20,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,19]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,22]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,25]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose>0,28]))
summary_tab_nose_2[21:24,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,19]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,22]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,25]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_nose<=0,28]))


tiff("Plot_nose_2.tiff",
     width =11, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_nose_2, aes(x = TimePoint, y = Average, colour = Season)) + 
  facet_wrap(~Trend)+
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['nose']*(~degree*C)))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  ylim(15,35)+
  theme(
      axis.text=element_text(size=19), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.position = c(.902, 0.105),
      legend.key.width= unit(1.1, 'cm'),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"),
      strip.text.x = element_text(size = 30))
dev.off()


#####

summary_tab_eye_2 = data.frame(TimePoint = rep(c("Control", "After Hike", "15 min", "30 min"),6))


summary_tab_eye_2$Average = rep(NA,24)
summary_tab_eye_2$SE = rep(NA,24)
summary_tab_eye_2$Season = c(rep("Spring",8), rep("Summer",8), rep("Winter",8))

summary_tab_eye_2 = summary_tab_eye_2 %>% mutate(TimePoint = factor(TimePoint, level = c("Control", "After Hike", "15 min", "30 min")))
summary_tab_eye_2$Trend = rep(c(rep("Increasing",4), rep("Decreasing",4)),3)

summary_tab_eye_2[1:4,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,20]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,23]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,26]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,29]))
summary_tab_eye_2[5:8,2]= c(mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,20]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,23]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,26]),
                                 mean(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,29]))

summary_tab_eye_2[9:12,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,20]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,23]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,26]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,29]))

summary_tab_eye_2[13:24,2]= c(mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,20]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,23]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,26]),
                                 mean(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,29]))

summary_tab_eye_2[17:20,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,20]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,23]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,26]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,29]))

summary_tab_eye_2[21:24,2]= c(mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,20]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,23]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,26]),
                                 mean(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,29]))

summary_tab_eye_2[1:4,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,20]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,23]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,26]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_eye>0,29]))
summary_tab_eye_2[5:8,3]= c(se(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,20]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,23]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,26]),
                                 se(May_merged_cleaned[May_merged_cleaned$Slopes_eye<=0,29]))

summary_tab_eye_2[9:12,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,20]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,23]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,26]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye>0,29]))
summary_tab_eye_2[13:16,3]= c(se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,20]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,23]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,26]),
                                 se(JJ_merged_cleaned[JJ_merged_cleaned$Slopes_eye<=0,29]))
summary_tab_eye_2[17:20,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,20]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,23]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,26]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye>0,29]))
summary_tab_eye_2[21:24,3]= c(se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,20]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,23]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,26]),
                                 se(ND_merged_cleaned[ND_merged_cleaned$Slopes_eye<=0,29]))

tiff("Plot_eye_2.tiff",
     width =11, height =7.0,
         units = "in", res =300)
ggplot(summary_tab_eye_2, aes(x = TimePoint, y = Average, colour = Season)) + 
  facet_wrap(~Trend)+
  geom_errorbar(aes(ymin = Average-SE, ymax = Average+SE), width = 0.2,size =1) +
  geom_line(aes(group = Season))+
  geom_point(size = 4) + theme_bw()+ylab(expression("T"['eye']*~(degree*C) ))+xlab("Time")+
  scale_color_manual(values = c("green","red", "blue"))+
  guides(linetype = guide_legend(override.aes = list(size = 3)))+
  theme(
      axis.text=element_text(size=19), axis.title = element_text(size = 32),
      legend.title = element_blank(), legend.text = element_text(size =24),
      legend.key.width= unit(1.1, 'cm'),
      legend.position = c(.902, 0.105),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"),
      strip.text.x = element_text(size = 30))
dev.off()
```

```{r Plotting Humidity and Temperature, message=F, warning=F, echo=F,eval =F}
weather_summary = mixed.dat_ear_2 %>% group_by(Season) %>%
  summarize(AvgTa = mean(Ta), AvgHumid = mean(Humid),SETa = se(Ta),SEHumid = se(Humid))

weather_summary$Season = c("Summer", "Spring", "Winter")
weather_summary = weather_summary %>% mutate(Season = factor(Season, level = c("Spring", "Summer", "Winter")))

ggplot(weather_summary, aes(x = Season, y = AvgTa)) + 
  geom_errorbar(aes(ymin = AvgTa-SETa, ymax = AvgTa+SETa), width = 0.2) +
  geom_line(aes(group = Season))+
  geom_point() + theme_bw() +geom_hline(yintercept = 0)+
  ylab(expression("T"['atmospheric']*" (C)"))+xlab("Season")+
  theme(
      axis.text=element_text(size=28), axis.title = element_text(size = 29),
      legend.title = element_text(size= 24), legend.text = element_text(size =24),
      legend.position = c(.87, .867),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"))
  

ggplot(weather_summary, aes(x = Season, y = AvgHumid)) + 
  geom_errorbar(aes(ymin = AvgHumid-SEHumid, ymax = AvgHumid+SEHumid), width = 0.2) +
  geom_line(aes(group = Season))+
  geom_point() + theme_bw()+ylab(expression("Humidity"*" (%)"))+xlab("Season")+
  theme(
      axis.text=element_text(size=28), axis.title = element_text(size = 29),
      legend.title = element_text(size= 24), legend.text = element_text(size =24),
      legend.position = c(.87, .867),
      panel.border = element_rect(colour = "black", fill=NA),
      legend.background = element_blank(),
      legend.box.background = element_rect(colour = "black"))
```
